#!/usr/bin/expect
spawn ./project2
expect ":"
send "1000\n"		
			#numpkt
expect ":"
send "0.10\n"	
			#loss
expect ":"
send "0.10\n"
			#corrupt
expect ":"
send ".10\n"
			#order
expect ":"
send "5\n"
			#time
expect ":"
send "0\n"
			#trace
expect ":"
send "1\n"
			#randomized
expect ":"
send "0\n"
			#bidirectional
# turn it back over to interactive user
interact