#!/usr/bin/expect
spawn ./project2
expect ":"
send "100\n"		
			#numpkt
expect ":"
send "0.01\n"	
			#loss
expect ":"
send "0.01\n"
			#corrupt
expect ":"
send ".01\n"
			#order
expect ":"
send "3\n"
			#time
expect ":"
send "0\n"
			#trace
expect ":"
send "0\n"
			#randomized
expect ":"
send "0\n"
			#bidirectional
# turn it back over to interactive user
interact